Repository aws-amplify/aws-sdk-android, pull requests merged in 2019-11, with the labels that each got.

#1272 [AWSMobileClient] Add non-null check in accessing fields of SignUpResult
  .idea/codeStyles/Project.xml
  .idea/vcs.xml
  CHANGELOG.md
  aws-android-sdk-mobile-client/src/androidTest/java/com/amazonaws/mobile/client/AWSMobileClientSignUpNoVerificationTest.java
  aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java
  aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/results/SignUpResult.java
Labels: AWSMobileClient, Pull Request

#1195 Add proxy support for iot connections
  CHANGELOG.md
  aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java
  aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotProxiedSSLSocket.java
  aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotProxiedSocketFactory.java
  aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotSslUtility.java
  aws-android-sdk-iot/src/test/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManagerTest.java
Labels: IoT, Pull Request

#1291 Update .gitignore
  .gitignore
Labels: Infrastructure, Pull Request

#1292 Update javadoc to warn against using BasicAWSCredentials
  aws-android-sdk-core/src/main/java/com/amazonaws/auth/BasicAWSCredentials.java
Labels: Core, Pull Request

#1266 [TransferUtility] Default notification id bug fix for Android Oreo & above
  CHANGELOG.md
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/mobileconnectors/s3/transferutility/DefaultNotificationIdTest.java
  aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferService.java
Labels: Pull Request, S3

#1240 [S3] content md5 in PutObjectResult
  CHANGELOG.md
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/PutFileIntegrationTest.java
  aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java
Labels: Pull Request, S3

#1331 Update CHANGELOG for model updates in 2.16.5
  CHANGELOG.md
Labels: Infrastructure, Pull Request
