Repository aws-amplify/aws-sdk-android, pull requests merged in 2019-06, with the labels that each got.

#1002 Add AWSConfiguration(JSONObject) constructor
  CHANGELOG.md
  aws-android-sdk-core/src/main/java/com/amazonaws/mobile/config/AWSConfiguration.java
  aws-android-sdk-core/src/test/java/com/amazonaws/mobile/config/AWSConfigurationTest.java
Labels: Core, Pull Request

#1010 Update CHANGELOG.md
  CHANGELOG.md
Labels: Pull Request, Transcribe

#1021 [MobileClient] Fix idiosyncrasy with declared minSdkVersion
  aws-android-sdk-mobile-client/build.gradle
  aws-android-sdk-mobile-client/src/androidTest/AndroidManifest.xml
Labels: AWSMobileClient, Infrastructure

#1022 [Docs] Update constructor recommendation for credentials provider
  aws-android-sdk-autoscaling/src/main/java/com/amazonaws/services/autoscaling/AmazonAutoScalingClient.java
  aws-android-sdk-cloudwatch/src/main/java/com/amazonaws/services/cloudwatch/AmazonCloudWatchClient.java
  aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/services/cognitoidentityprovider/AmazonCognitoIdentityProviderClient.java
  aws-android-sdk-comprehend/src/main/java/com/amazonaws/services/comprehend/AmazonComprehendClient.java
  aws-android-sdk-core/src/main/java/com/amazonaws/services/cognitoidentity/AmazonCognitoIdentityClient.java
  aws-android-sdk-core/src/main/java/com/amazonaws/services/securitytoken/AWSSecurityTokenServiceClient.java
  aws-android-sdk-ddb/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBClient.java
  aws-android-sdk-elb/src/main/java/com/amazonaws/services/elasticloadbalancing/AmazonElasticLoadBalancingClient.java
  aws-android-sdk-iot/src/main/java/com/amazonaws/services/iot/AWSIotClient.java
  aws-android-sdk-iot/src/main/java/com/amazonaws/services/iotdata/AWSIotDataClient.java
  aws-android-sdk-kinesis/src/main/java/com/amazonaws/services/kinesis/AmazonKinesisClient.java
  aws-android-sdk-kinesis/src/main/java/com/amazonaws/services/kinesisfirehose/AmazonKinesisFirehoseClient.java
  aws-android-sdk-kinesisvideo-archivedmedia/src/main/java/com/amazonaws/services/kinesisvideoarchivedmedia/AWSKinesisVideoArchivedMediaClient.java
  aws-android-sdk-kinesisvideo/src/main/java/com/amazonaws/services/kinesisvideo/AWSKinesisVideoClient.java
  aws-android-sdk-kms/src/main/java/com/amazonaws/services/kms/AWSKMSClient.java
  aws-android-sdk-lambda/src/main/java/com/amazonaws/services/lambda/AWSLambdaClient.java
  aws-android-sdk-lex/src/main/java/com/amazonaws/services/lexrts/AmazonLexRuntimeClient.java
  aws-android-sdk-logs/src/main/java/com/amazonaws/services/logs/AmazonCloudWatchLogsClient.java
  aws-android-sdk-machinelearning/src/main/java/com/amazonaws/services/machinelearning/AmazonMachineLearningClient.java
  aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java
  aws-android-sdk-pinpoint/src/main/java/com/amazonaws/services/pinpoint/AmazonPinpointClient.java
  aws-android-sdk-pinpoint/src/main/java/com/amazonaws/services/pinpointanalytics/AmazonPinpointAnalyticsClient.java
  aws-android-sdk-polly/src/main/java/com/amazonaws/services/polly/AmazonPollyClient.java
  aws-android-sdk-polly/src/main/java/com/amazonaws/services/polly/AmazonPollyPresigningClient.java
  aws-android-sdk-rekognition/src/main/java/com/amazonaws/services/rekognition/AmazonRekognitionClient.java
  aws-android-sdk-ses/src/main/java/com/amazonaws/services/simpleemail/AmazonSimpleEmailServiceClient.java
  aws-android-sdk-sns/src/main/java/com/amazonaws/services/sns/AmazonSNSClient.java
  aws-android-sdk-sqs/src/main/java/com/amazonaws/services/sqs/AmazonSQSClient.java
  aws-android-sdk-transcribe/src/main/java/com/amazonaws/services/transcribe/AmazonTranscribeClient.java
  aws-android-sdk-translate/src/main/java/com/amazonaws/services/translate/AmazonTranslateClient.java
Labels: Documentation

#1044 [S3] Fix ConcurrentModificationException in pauseAllTransfersDueToNetworkInterruption #777
  CHANGELOG.md
  aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/S3ClientReference.java
  aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferStatusUpdater.java
Labels: Pull Request, S3

#1052 Palpatim/merge from master
  aws-android-sdk-cloudwatch/src/main/java/com/amazonaws/services/cloudwatch/AmazonCloudWatchClient.java
  aws-android-sdk-ddb/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBClient.java
  aws-android-sdk-iot/src/main/java/com/amazonaws/services/iotdata/AWSIotDataClient.java
  aws-android-sdk-kinesis/src/main/java/com/amazonaws/services/kinesis/AmazonKinesisClient.java
  aws-android-sdk-kinesisvideo-archivedmedia/src/main/java/com/amazonaws/services/kinesisvideoarchivedmedia/AWSKinesisVideoArchivedMediaClient.java
  aws-android-sdk-logs/src/main/java/com/amazonaws/services/logs/AmazonCloudWatchLogsClient.java
  aws-android-sdk-mobile-client/build.gradle
  aws-android-sdk-mobile-client/src/androidTest/AndroidManifest.xml
  aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java
  aws-android-sdk-pinpoint/src/main/java/com/amazonaws/services/pinpoint/AmazonPinpointClient.java
  aws-android-sdk-pinpoint/src/main/java/com/amazonaws/services/pinpointanalytics/AmazonPinpointAnalyticsClient.java
  aws-android-sdk-polly/src/main/java/com/amazonaws/services/polly/AmazonPollyPresigningClient.java
  aws-android-sdk-rekognition/src/main/java/com/amazonaws/services/rekognition/AmazonRekognitionClient.java
  aws-android-sdk-sns/src/main/java/com/amazonaws/services/sns/AmazonSNSClient.java
  aws-android-sdk-sqs/src/main/java/com/amazonaws/services/sqs/AmazonSQSClient.java
  aws-android-sdk-transcribe/src/main/java/com/amazonaws/services/transcribe/AmazonTranscribeClient.java
Labels: Build, Pull Request

#1047 Adding SageMakerRuntime API
  .idea/modules.xml
  CircleciScripts/ReleaseConfiguration.json
  aws-android-sdk-core/src/main/java/com/amazonaws/internal/config/InternalConfig.java
  aws-android-sdk-sagemaker-runtime-test/build.gradle
  aws-android-sdk-sagemaker-runtime-test/proguard-rules.pro
  aws-android-sdk-sagemaker-runtime-test/src/androidTest/java/com/amazonaws/services/sagemakerruntime/AmazonSageMakerRuntimeIntegrationTest.java
  aws-android-sdk-sagemaker-runtime-test/src/androidTest/java/com/amazonaws/services/sagemakerruntime/AmazonSageMakerRuntimeTestBase.java
  aws-android-sdk-sagemaker-runtime-test/src/main/AndroidManifest.xml
  aws-android-sdk-sagemaker-runtime-test/src/main/res/values/strings.xml
  aws-android-sdk-sagemaker-runtime/build.gradle
  aws-android-sdk-sagemaker-runtime/pom.xml
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/AmazonSageMakerRuntime.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/AmazonSageMakerRuntimeAsync.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/AmazonSageMakerRuntimeAsyncClient.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/AmazonSageMakerRuntimeClient.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/InternalFailureException.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/InvokeEndpointRequest.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/InvokeEndpointResult.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/ModelErrorException.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/ServiceUnavailableException.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/ValidationErrorException.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/package-info.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/transform/InternalFailureExceptionUnmarshaller.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/transform/InvokeEndpointRequestMarshaller.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/transform/InvokeEndpointResultJsonUnmarshaller.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/transform/ModelErrorExceptionUnmarshaller.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/transform/ServiceUnavailableExceptionUnmarshaller.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/transform/ValidationErrorExceptionUnmarshaller.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/model/transform/package-info.java
  aws-android-sdk-sagemaker-runtime/src/main/java/com/amazonaws/services/sagemakerruntime/package-info.java
  pom.xml
  settings.gradle
Labels: Pull Request, SageMakerRuntime

#1054 Added SagemakerRuntime to CircleCI script
  .circleci/config.yml
Labels: Pull Request, SageMakerRuntime

#1058 [Pinpoint] Fix a bug that batches more than 100 events
  CHANGELOG.md
  aws-android-sdk-pinpoint/src/main/java/com/amazonaws/mobileconnectors/pinpoint/internal/event/EventRecorder.java
  aws-android-sdk-pinpoint/src/test/java/com/amazonaws/mobileconnectors/pinpoint/analytics/AnalyticsClientTest.java
  aws-android-sdk-pinpoint/src/test/java/com/amazonaws/mobileconnectors/pinpoint/internal/event/EventRecorderTest.java
Labels: Pinpoint, Pull Request
