Repository aws-amplify/aws-sdk-android, pull requests merged in 2019-01, with the labels that each got.

#642 configure circleci
  .circleci/config.yml
  .gitignore
  CircleciScripts/JavaDoc.css
  CircleciScripts/ReleaseConfiguration.json
  CircleciScripts/check_testresult.sh
  CircleciScripts/cloudfront_invalidate.py
  CircleciScripts/copy_libs.py
  CircleciScripts/copy_resourcefiles.py
  CircleciScripts/functions.py
  CircleciScripts/generate_javadoc.py
  CircleciScripts/maven_release.sh
  CircleciScripts/mvnhome/settings.xml
  CircleciScripts/preserve_olddocument.sh
  CircleciScripts/run_unittest.py
  CircleciScripts/s3_maven.py
  CircleciScripts/samples.html
  CircleciScripts/source.html
  aws-android-sdk-auth-core/pom.xml
  aws-android-sdk-auth-facebook/pom.xml
  aws-android-sdk-auth-google/pom.xml
  aws-android-sdk-auth-ui/pom.xml
  aws-android-sdk-auth-userpools/pom.xml
  aws-android-sdk-cognitoauth/pom.xml
  aws-android-sdk-iot/build.gradle
  aws-android-sdk-kinesis/src/test/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/FileRecordStoreTest.java
  aws-android-sdk-kinesisvideo/pom.xml
  aws-android-sdk-lex/pom.xml
  aws-android-sdk-mobile-client/pom.xml
  aws-android-sdk-pinpoint/pom.xml
  gradle/wrapper/gradle-wrapper.jar
  pom.xml
Labels: Infrastructure, pull request

#651 Update maven_release.sh
  CircleciScripts/maven_release.sh
Labels: Infrastructure, pull request

#653 Update config.yml to store maven artifacts from build
  .circleci/config.yml
Labels: Infrastructure, pull request

#654 Update config.yml
  .circleci/config.yml
Labels: Infrastructure, pull request

#655 Debug maven release folder structure
  .circleci/config.yml
  CircleciScripts/maven_release.sh
Labels: Infrastructure, pull request

#660 [Fix] [IoT] Check scheduleReconnect() return value
  aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java
Labels: IoT, bug, pull request

#673 Fix cognito userpools username null in custom auth flow fixes #583
  aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java
Labels: Cognito, pull request
