Repository aws-amplify/aws-sdk-android, pull requests merged in 2019-02, with the labels that each got.

#688 [MobileClient] Clarify federatedSignIn method functionality
  aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java
Labels: AWSMobileClient, Documentation

#690 Update gitignore and .idea modules
  .gitignore
  .idea/misc.xml
  .idea/modules.xml
Labels: Infrastructure, Pull Request

#689 Add srp_a and password verifier support for custom auth flow
  aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java
  aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/continuations/AuthenticationDetails.java
Labels: Cognito, Pull Request

#692 [Infra] Add command to generate gradle wrapper
  .circleci/config.yml
Labels: Infrastructure, Pull Request

#698 [Infra] Install gradle and generate wrapper
  .circleci/config.yml
Labels: Infrastructure, Pull Request

#697 Update bug_report.md reproduction steps to code
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Documentation, Infrastructure, Pull Request

#701 [Core] Add callback and internal returning runnable
  aws-android-sdk-core/src/main/java/com/amazonaws/async/Callback.java
  aws-android-sdk-core/src/main/java/com/amazonaws/internal/ReturningRunnable.java
Labels: Core, Pull Request

#702 [Userpools] Fix network calls to run in background when specified fixes #668
  aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java
  aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool.java
Labels: Cognito, Pull Request

#721 Update config.yml
  .circleci/config.yml
Labels: Infrastructure, Pull Request

#724 Integration tests for aws-android-sdk-kinesis module
  aws-android-sdk-kinesis-test/.gitignore
  aws-android-sdk-kinesis-test/build.gradle
  aws-android-sdk-kinesis-test/proguard-rules.pro
  aws-android-sdk-kinesis-test/src/androidTest/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/KinesisFirehoseRecorderIntegrationTest.java
  aws-android-sdk-kinesis-test/src/androidTest/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/KinesisRecorderIntegrationTest.java
  aws-android-sdk-kinesis-test/src/androidTest/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/KinesisRecorderIntegrationTestBase.java
  aws-android-sdk-kinesis-test/src/androidTest/java/com/amazonaws/services/kinesis/KinesisIntegrationTest.java
  aws-android-sdk-kinesis-test/src/androidTest/java/com/amazonaws/services/kinesis/KinesisIntegrationTestBase.java
  aws-android-sdk-kinesis-test/src/main/AndroidManifest.xml
  aws-android-sdk-kinesis-test/src/main/res/values/strings.xml
  aws-android-sdk-testutils/src/main/java/com/amazonaws/testutils/AWSTestBase.java
  settings.gradle
Labels: Infrastructure, Pull Request

#725 Integration tests for aws-android-sdk-autoscaling module
  aws-android-sdk-autoscaling-test/.gitignore
  aws-android-sdk-autoscaling-test/build.gradle
  aws-android-sdk-autoscaling-test/proguard-rules.pro
  aws-android-sdk-autoscaling-test/src/androidTest/java/com/amazonaws/services/autoscaling/AutoScalingIntegrationTest.java
  aws-android-sdk-autoscaling-test/src/androidTest/java/com/amazonaws/services/autoscaling/AutoScalingIntegrationTestBase.java
  aws-android-sdk-autoscaling-test/src/main/AndroidManifest.xml
  aws-android-sdk-autoscaling-test/src/main/res/values/strings.xml
  settings.gradle
Labels: Infrastructure, Pull Request

#729 Integration tests for aws-android-sdk-cloudwatch module
  CircleciScripts/run_integrationtest.py
  aws-android-sdk-cloudwatch-test/.gitignore
  aws-android-sdk-cloudwatch-test/build.gradle
  aws-android-sdk-cloudwatch-test/proguard-rules.pro
  aws-android-sdk-cloudwatch-test/src/androidTest/java/com/amazonaws/services/cloudwatch/CloudWatchIntegrationTest.java
  aws-android-sdk-cloudwatch-test/src/androidTest/java/com/amazonaws/services/cloudwatch/CloudWatchIntegrationTestBase.java
  aws-android-sdk-cloudwatch-test/src/androidTest/java/com/amazonaws/services/logs/CloudWatchLogIntegrationTest.java
  aws-android-sdk-cloudwatch-test/src/main/AndroidManifest.xml
  aws-android-sdk-cloudwatch-test/src/main/res/values/strings.xml
  settings.gradle
Labels: Infrastructure, Pull Request

#730 Integration tests for aws-android-sdk-comprehend module
  CircleciScripts/run_integrationtest.py
  aws-android-sdk-comprehend-test/.gitignore
  aws-android-sdk-comprehend-test/build.gradle
  aws-android-sdk-comprehend-test/proguard-rules.pro
  aws-android-sdk-comprehend-test/src/androidTest/java/com/amazonaws/services/comprehend/ComprehendIntegrationTest.java
  aws-android-sdk-comprehend-test/src/main/AndroidManifest.xml
  aws-android-sdk-comprehend-test/src/main/res/values/strings.xml
  settings.gradle
Labels: Infrastructure, Pull Request

#731 Integration tests for aws-android-sdk-polly-test
  CircleciScripts/run_integrationtest.py
  aws-android-sdk-polly-test/.gitignore
  aws-android-sdk-polly-test/build.gradle
  aws-android-sdk-polly-test/proguard-rules.pro
  aws-android-sdk-polly-test/src/androidTest/assets/four-to-eight.pls
  aws-android-sdk-polly-test/src/androidTest/assets/one-to-two.pls
  aws-android-sdk-polly-test/src/androidTest/java/com/amazonaws/services/polly/PollyPresigningIntegrationTest.java
  aws-android-sdk-polly-test/src/main/AndroidManifest.xml
  aws-android-sdk-polly-test/src/main/res/values/strings.xml
  settings.gradle
Labels: Infrastructure, Pull Request

#732 Integration tests for aws-android-sdk-rekognition module
  CircleciScripts/run_integrationtest.py
  aws-android-sdk-rekognition-test/.gitignore
  aws-android-sdk-rekognition-test/build.gradle
  aws-android-sdk-rekognition-test/proguard-rules.pro
  aws-android-sdk-rekognition-test/src/androidTest/assets/canyon.jpg
  aws-android-sdk-rekognition-test/src/androidTest/java/com/amazonaws/services/rekognition/RekognitionIntegrationTest.java
  aws-android-sdk-rekognition-test/src/main/AndroidManifest.xml
  aws-android-sdk-rekognition-test/src/main/res/drawable/canyon.jpg
  aws-android-sdk-rekognition-test/src/main/res/values/strings.xml
  settings.gradle
Labels: Infrastructure, Pull Request

#733 Integration tests for DynamoDB
  CircleciScripts/run_integrationtest.py
  aws-android-sdk-ddb-test/.gitignore
  aws-android-sdk-ddb-test/build.gradle
  aws-android-sdk-ddb-test/proguard-rules.pro
  aws-android-sdk-ddb-test/src/androidTest/java/com/amazonaws/mobileconnectors/dynamodbv2/DocumentCRUDIntegrationTest.java
  aws-android-sdk-ddb-test/src/androidTest/java/com/amazonaws/mobileconnectors/dynamodbv2/DynamoDBIntegrationTestBase.java
  aws-android-sdk-ddb-test/src/androidTest/java/com/amazonaws/mobileconnectors/dynamodbv2/SearchIntegrationTest.java
  aws-android-sdk-ddb-test/src/main/AndroidManifest.xml
  aws-android-sdk-ddb-test/src/main/res/values/strings.xml
  settings.gradle
Labels: Infrastructure, Pull Request

#734 Integration tests for ELB
  CircleciScripts/run_integrationtest.py
  aws-android-sdk-elb-test/.gitignore
  aws-android-sdk-elb-test/build.gradle
  aws-android-sdk-elb-test/proguard-rules.pro
  aws-android-sdk-elb-test/src/androidTest/java/com/amazonaws/services/elasticloadbalancing/ElbIntegrationTest.java
  aws-android-sdk-elb-test/src/main/AndroidManifest.xml
  aws-android-sdk-elb-test/src/main/res/values/strings.xml
  settings.gradle
Labels: Infrastructure, Pull Request

#743 Integration tests for Kinesisvideo module
  CircleciScripts/run_integrationtest.py
  aws-android-sdk-kinesisvideo/build.gradle
  aws-android-sdk-kinesisvideo/src/androidTest/java/com/amazonaws/services/kinesisvideo/KinesisVideoIntegrationTest.java
  aws-android-sdk-kinesisvideo/src/androidTest/java/com/amazonaws/services/kinesisvideo/KinesisVideoIntegrationTestBase.java
  aws-android-sdk-kinesisvideo/src/main/AndroidManifest.xml
  aws-android-sdk-kinesisvideo/src/main/res/values/strings.xml
Labels: Infrastructure, Pull Request

#744 Kinesisvideo archivedmedia integration tests
  CircleciScripts/run_integrationtest.py
  aws-android-sdk-kinesisvideo-archivedmedia/build.gradle
  aws-android-sdk-kinesisvideo-archivedmedia/src/androidTest/java/com/amazonaws/services/kinesisvideoarchivedmedia/KinesisVideoArchivedMediaIntegrationTest.java
  aws-android-sdk-kinesisvideo-archivedmedia/src/androidTest/java/com/amazonaws/services/kinesisvideoarchivedmedia/KinesisVideoArchivedMediaIntegrationTestBase.java
  aws-android-sdk-kinesisvideo-archivedmedia/src/main/res/values/strings.xml
  aws-android-sdk-testutils/build.gradle
Labels: Infrastructure, Pull Request

#745 Integration test for SimpleDB SDK module
  CircleciScripts/run_integrationtest.py
  aws-android-sdk-sdb-test/.gitignore
  aws-android-sdk-sdb-test/build.gradle
  aws-android-sdk-sdb-test/proguard-rules.pro
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/AuthenticationErrorsIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/BatchPutAttributesIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/ClockSkewIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/CreateDomainIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/DeleteAttributesIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/DeleteDomainIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/DomainMetadataIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/GetAttributesIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/InvalidXmlCharactersIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/ListDomainsIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/PutAttributesIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/RequestHandlersIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/SelectIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/SimpleDBIntegrationTest.java
  aws-android-sdk-sdb-test/src/androidTest/java/com/amazonaws/services/simpledb/SimpleDBIntegrationTestBase.java
  aws-android-sdk-sdb-test/src/main/AndroidManifest.xml
  aws-android-sdk-sdb-test/src/main/res/values/strings.xml
  aws-android-sdk-sdb-test/src/test/java/com/amazonaws/services/simpledb/SimpleDBResponseMetadataTests.java
  settings.gradle
Labels: Infrastructure, Pull Request

#746 Integration test for S3 SDK
  CircleciScripts/run_integrationtest.py
  aws-android-sdk-s3-test/.gitignore
  aws-android-sdk-s3-test/build.gradle
  aws-android-sdk-s3-test/proguard-rules.pro
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/auth/policy/S3PolicyIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/AccelerateIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/AclIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/AmazonS3ClientIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/BucketCrossOriginConfigurationIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/BucketLifecycleConfigurationIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/BucketLoggingIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/BucketNameValidationIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/BucketPolicyIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/BucketReplicationIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/BucketTaggingIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/BucketWebsiteIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/CleanupBucketIntegrationTests.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/ClockSkewIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/CopyObjectIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/CopyPartIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/ExceptionHandlingIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/ExpectContinueIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/GetObjectIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/LifecycleVersioningIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/MultiObjectDeleteIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/MultiPartUploadsIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/MultiThreadedDownloadIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/PresignedUrlIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/PutFileIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/PutStreamIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/RequestHandlerIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/RestoreObjectIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/S3IntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/S3IntegrationTestBase.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/S3InterruptIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/S3ListObjectsIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/S3ListObjectsV2IntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/S3SkipByteDigestIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/STSIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/ServerSideEncryptionWithCustomerKeyIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/SpecialObjectKeyNameIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/StorageClassIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/UnauthenticatedIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/V1BucketAddressingIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/VersioningIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/XmlSanitizingIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/internal/crypto/CryptoTestUtils.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/iterable/S3ObjectsIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/iterable/S3VersionsIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/model/GeneratePresignedUrlRequestIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/model/UrlEncodingIntegrationTest.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/samplePolicy.json
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/util/SpecialObjectKeyNameGenerator.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/util/StreamUtils.java
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/util/UnreliableRepeatableFileInputStream.java
  aws-android-sdk-s3-test/src/main/AndroidManifest.xml
  aws-android-sdk-s3-test/src/main/res/values/strings.xml
  settings.gradle
Labels: Infrastructure, Pull Request
