Repository aws-amplify/aws-sdk-android, pull requests merged in 2019-07, with the labels that each got.

#1060 Add changelog details for SageMaker
  CHANGELOG.md
Labels: Pull Request, SageMakerRuntime

#1064 [bump version 2.13.7]
  aws-android-sdk-apigateway-core/pom.xml
  aws-android-sdk-auth-core/pom.xml
  aws-android-sdk-auth-facebook/pom.xml
  aws-android-sdk-auth-google/pom.xml
  aws-android-sdk-auth-ui/pom.xml
  aws-android-sdk-auth-userpools/pom.xml
  aws-android-sdk-autoscaling/pom.xml
  aws-android-sdk-cloudwatch/pom.xml
  aws-android-sdk-cognito/pom.xml
  aws-android-sdk-cognito/src/main/resources/fabric/com.amazonaws.aws-android-sdk-cognito.properties
  aws-android-sdk-cognitoauth/pom.xml
  aws-android-sdk-cognitoidentityprovider/pom.xml
  aws-android-sdk-comprehend/pom.xml
  aws-android-sdk-core/pom.xml
  aws-android-sdk-core/src/main/java/com/amazonaws/util/VersionInfoUtils.java
  aws-android-sdk-core/src/main/resources/fabric/com.amazonaws.aws-android-sdk-core.properties
  aws-android-sdk-core/src/test/java/com/amazonaws/util/VersionInfoUtilsTest.java
  aws-android-sdk-ddb-document/pom.xml
  aws-android-sdk-ddb-mapper/pom.xml
  aws-android-sdk-ddb/pom.xml
  aws-android-sdk-ec2/pom.xml
  aws-android-sdk-elb/pom.xml
  aws-android-sdk-iot/pom.xml
  aws-android-sdk-kinesis/pom.xml
  aws-android-sdk-kinesisvideo-archivedmedia/pom.xml
  aws-android-sdk-kinesisvideo/pom.xml
  aws-android-sdk-kms/pom.xml
  aws-android-sdk-lambda/pom.xml
  aws-android-sdk-lex/pom.xml
  aws-android-sdk-logs/pom.xml
  aws-android-sdk-machinelearning/pom.xml
  aws-android-sdk-mobile-client/pom.xml
  aws-android-sdk-mobileanalytics/pom.xml
  aws-android-sdk-pinpoint/pom.xml
  aws-android-sdk-polly/pom.xml
  aws-android-sdk-rekognition/pom.xml
  aws-android-sdk-s3/pom.xml
  aws-android-sdk-sagemaker-runtime/pom.xml
  aws-android-sdk-sdb/pom.xml
  aws-android-sdk-ses/pom.xml
  aws-android-sdk-sns/pom.xml
  aws-android-sdk-sqs/pom.xml
  aws-android-sdk-textract/pom.xml
  aws-android-sdk-transcribe/pom.xml
  aws-android-sdk-translate/pom.xml
  pom.xml
Labels: Pull Request

#1069 [aws-android-sdk-kinesisvideo] Update models to latest
  aws-android-sdk-kinesisvideo/src/main/java/com/amazonaws/services/kinesisvideo/model/APIName.java
  aws-android-sdk-kinesisvideo/src/main/java/com/amazonaws/services/kinesisvideo/model/GetDataEndpointRequest.java
Labels: KinesisVideo, Pull Request

#1071 Update CHANGELOG
  CHANGELOG.md
Labels: Documentation, Pull Request

#1076 [S3] Fix testRoundTrip to wait for lifecycle configuration to be created
  aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/LifecycleVersioningIntegrationTest.java
Labels: Pull Request, S3

#1080 Update CHANGELOG
  CHANGELOG.md
Labels: Documentation, Pull Request

#1084 Fix Tags Field in CreateStreamRequest Caused ValidationException
  CHANGELOG.md
  aws-android-sdk-kinesisvideo/src/main/java/com/amazonaws/mobileconnectors/kinesisvideo/service/KinesisVideoAndroidServiceClient.java
Labels: KinesisVideo, Pull Request

#1089 Fixed response unmarshalling with gzip encoding
  .idea/modules.xml
  CHANGELOG.md
  README.md
  aws-android-sdk-core/src/main/java/com/amazonaws/http/JsonResponseHandler.java
  aws-android-sdk-core/src/test/java/com/amazonaws/auth/AWS3SignerTest.java
  aws-android-sdk-core/src/test/java/com/amazonaws/auth/policy/PolicyReaderTest.java
  aws-android-sdk-ddb-mapper-test/src/androidTest/java/com/amazonaws/mobileconnectors/dynamodbv2/dynamodbmapper/BatchLoadIntegrationTest.java
  aws-android-sdk-kinesis-test/src/androidTest/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/KinesisRecorderIntegrationTest.java
Labels: Core, Pull Request

#1091 Fix the timestamp unit for media codec encoder
  CHANGELOG.md
  aws-android-sdk-kinesisvideo/src/main/java/com/amazonaws/mobileconnectors/kinesisvideo/encoding/EncoderFrameSubmitter.java
Labels: KinesisVideo, Pull Request

#1095 Fix IoT assertion during integ test setup
  aws-android-sdk-iot/src/androidTest/java/com/amazonaws/mobileconnectors/iot/MqttManagerIntegrationTest.java
Labels: IoT, Pull Request

#1098 Support me-south-1 region
  CHANGELOG.md
  aws-android-sdk-core/src/main/java/com/amazonaws/regions/RegionDefaults.java
  aws-android-sdk-core/src/main/java/com/amazonaws/regions/Regions.java
  aws-android-sdk-core/src/test/java/com/amazonaws/regions/RegionUtilsTest.java
  aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/model/Region.java
Labels: Core, Pull Request

#1097 Added local testing support for S3
  aws-android-sdk-s3/pom.xml
  aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.java
  aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java
  aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/S3ClientOptions.java
  aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/Constants.java
  aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/ServiceUtils.java
  aws-android-sdk-s3/src/test/java/com/amazonaws/services/s3/S3ClientOptionsTest.java
  aws-android-sdk-s3/src/test/java/com/amazonaws/services/s3/TransferUtilityTest.java
  aws-android-sdk-s3/src/test/java/com/amazonaws/services/s3/internal/ServiceUtilsTest.java
Labels: Pull Request, S3

#1102 Use gradle wrapper from source control
  .circleci/config.yml
  gradle/wrapper/gradle-wrapper.jar
Labels: Build
